include ../../../../../config.mk
include ../../../../../Makefile.inc

FILES = \
	tile.png

all:
	@echo no-op

install: $(FILES)
	install -m 755 -d $(DESTDIR)$(datarootdir)/images/teallach/wallpapers
	install -m644 $^ $(DESTDIR)$(datarootdir)/images/teallach/wallpapers
