include ../../../../../Makefile.inc

FILES = \
	tile.png

all:
	@echo no-op

install: $(FILES)
	@mkdir -p $(DESTDIR)$(datarootdir)/images/teallach/wallpapers
	install -m644 $^ $(DESTDIR)$(datarootdir)/images/teallach/wallpapers
